Repository StackStorm/st2ci, pull requests merged in 2020-04, with the labels that each got.

#171 Remove Ubuntu 14 actions and rules
  actions/bwc_pkg_promote_all.meta.yaml
  actions/st2_pkg_e2e_test.meta.yaml
  actions/st2_pkg_promote_all.meta.yaml
  actions/st2_pkg_test_and_promote.meta.yaml
  actions/st2_pkg_test_and_promote_enterprise.meta.yaml
  actions/st2_pkg_upgrade_deb.meta.yaml
  actions/st2_pkg_upgrade_deps_u14.meta.yaml
  actions/st2_pkg_upgrade_deps_u14.sh
  actions/st2_pkg_upgrade_e2e_test.meta.yaml
  actions/workflows/bwc_pkg_promote_all.yaml
  actions/workflows/run_all_nightlies.yaml
  actions/workflows/st2_pkg_promote_all.yaml
  actions/workflows/st2_pkg_test_and_promote.yaml
  actions/workflows/st2_pkg_upgrade_deb.yaml
  rules/st2_pkg_test_and_promote_unstable_u14.yaml
  rules/st2_pkg_test_and_promote_unstable_u14_enterprise.yaml
  rules/st2_pkg_test_unstable_u14.yaml
  rules/st2_pkg_test_unstable_u14_dev.yaml
  rules/st2_pkg_test_unstable_u14_enterprise.yaml
  rules/st2_pkg_test_unstable_u14_enterprise_dev.yaml
  rules/st2_pkg_test_unstable_u14_enterprise_packaging.yaml
  rules/st2_pkg_test_unstable_u14_packaging.yaml
Labels: enhancement

#172 Promote packages in series after all
  actions/workflows/bwc_pkg_promote_all.yaml
Labels: bug

#174 Fix CentOS8 CI rule for st2 PR github status
  rules/st2_pkg_e2e_test_centos8_on_st2_pr.yaml
Labels: bug

#182 Fixing package upgrade e2e test for u18 and el8
  actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Labels: bug

#178 Fix syntax error in st2_pkg_upgrade_rpm
  actions/workflows/st2_pkg_upgrade_rpm.yaml
Labels: bug

#181 removing extra fi
  actions/st2_pkg_upgrade_deps_el8.sh
Labels: OS support, bug

#183 Added explicit check for all OSes
  actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Labels: enhancement

#184 Skip mistral SQL migrations on modern OSes that don't install Mistral
  actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Labels: bug

#186 Fixing upgrade e2e tests to verify distro in proper branch
  actions/workflows/st2_pkg_upgrade_e2e_test.yaml
Labels: bug
